<a href="https://colab.research.google.com/github/CD-AC/Master_AI/blob/main/DataScience_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt

# Arrays Numpy

In [2]:
temp = np.array([33])
print(type(temp))
print(temp)

<class 'numpy.ndarray'>
[33]


In [3]:
vector = np.array([30, 31, 32, 33, 34, 32, 33])
print(vector)

[30 31 32 33 34 32 33]


In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
tensor = np.array([[[ 1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
eye_matrix = np.eye(4)
print(eye_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
diag = np.diag([1, 2, 3, 4])
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [14]:
random = np.random.random((2,3))
print(random)

[[0.97217499 0.37843456 0.02523644]
 [0.4513829  0.44076098 0.73815433]]


In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

2
(2, 3)
6
int64


In [17]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [18]:
dobl = np.array([1, 2, 3], dtype= 'd' )
print(dobl)

[1. 2. 3.]


In [19]:
z = z.astype(np.float64)
print(z)

3.0


In [21]:
sum = np.array([[1, 2, 3], [4, 5, 6]])
add = np.sum (sum)
print(add)

21


In [22]:
mean = np.mean(sum)
print(mean)

3.5


In [23]:
std = np.std(sum)
print(std)

1.707825127659933


# Indexation And Slicing

In [25]:
array = np.array([[10, 20, 30, 40, 50]])
print(array[1])
print(array[-1])

IndexError: index 1 is out of bounds for axis 0 with size 1